# **Basic Introduction to NumPy: Problems**
 

This problem set is designed to test your understanding of fundamental NumPy concepts. The problems are based on a
 scenario involving daily operational data from a food service business. Your task is to use NumPy to solve these analytical
 challenges

# **Problem 1: Daily Revenue Analysis**

You have been given the daily revenue data for two weeks. The data is provided as a Python list. Your goal is to convert
This list into a NumPy array and perform basic analysis.
#### **Task 1.1**:Create a 1-D NumPy array named daily_revenue_lakhs from the provided list. The values are in Lakhs INR.
#### **Task 1.2**: Calculate and print the total revenue for the two weeks.
#### **Task 1.3:** Calculate and print the average daily revenue.
##### *Hint:Use the np.array() function to convert the list. NumPy arrays have built-in methods like .sum() and .mean() for easy calculations.*
 

In [13]:
import numpy as np
# Given data
daily_revenue_data = [
 5.5, 6.2, 5.8, 7.1, 7.5, 8.0, 9.2,
 6.0, 6.5, 7.0, 7.8, 8.5, 9.0, 9.5
 ]
 # Write your code below
daily_revenue_lakhs=np.array(daily_revenue_data)
print(f"The values are in Lakhs INR:{daily_revenue_lakhs}")

The values are in Lakhs INR:[5.5 6.2 5.8 7.1 7.5 8.  9.2 6.  6.5 7.  7.8 8.5 9.  9.5]


In [9]:
#Calculate and print the total revenue for the two weeks
total_revenue=np.sum(daily_revenue_lakhs)
print(total_revenue)

103.6


In [11]:
#Calculate and print the average daily revenue
avg_daily_revenue=np.mean(daily_revenue_lakhs)
print(avg_daily_revenue)

7.3999999999999995


# **Problem 2: Product and Cost Analysis**


The business tracks the quantity and cost of three main product types: 'Cups', 'Cones', and 'Specials'. The data is organized
 in a 2-D structure. You need to use a 2-D NumPy array to analyze this data
#### **Task 2.1:** Create a 2-D NumPy array named product_sales from the nested list. The first row represents units sold, and the second row represents cost per unit. The columns correspond to 'Cups', 'Cones', and 'Specials'.
#### **Task 2.2:** Use array indexing to print the total number of 'Cones' sold.
#### **Task 2.3:** Use array slicing to print the costs for 'Cones' and 'Specials'
##### *Hint: Remember that NumPy arrays are indexed starting from 0. For slicing, use the colon : notation.*

In [15]:
 # Given data
product_sales_data = [
 [1500, 2200, 800],  # Units sold for Cups, Cones, Specials
 [30, 20, 150]       
]
 # Cost per unit (in INR) for Cups, Cones, Specials
 # Write your code below this line
product_sales=np.array(product_sales_data)
print("Create a 2-D NumPy array:")
print(product_sales)

Create a 2-D NumPy array:
[[1500 2200  800]
 [  30   20  150]]


In [18]:
# Use array indexing to print the total number of 'Cones' sold
cone_indexing=product_sales[0,1]
print("array indexing to print the total number of 'Cones' sold:")
print(cone_indexing)

array indexing to print the total number of 'Cones' sold:
2200


In [27]:
# Use array slicing to print the costs for 'Cones' and 'Specials'
cones_specials_cost=product_sales[1,1:]
print("array slicing to print the costs for 'Cones' and 'Specials':")
print(cones_specials_cost)

array slicing to print the costs for 'Cones' and 'Specials':
[ 20 150]


# **Problem 3: Cost and Profit Calculations with Vectorization**

The business wants to automate cost and profit calculations. You have an array of unit costs and a fixed profit margin. You
need to use NumPy's vectorized operations to perform calculations efficiently without using a for loop.
#### **Task 3.1:** Create a 1-D NumPy array named unit_costs with the provided data.
#### **Task 3.2:** Define a variable profit_margin_percent with a value of 25.
#### **Task 3.3:** Calculate the selling price for each unit by adding the profit margin. 
#### The formula is: selling_price = unit_cost + (unit_cost * profit_margin_percent / 100). Store the result in a new array named selling_prices.
##### *Hint: NumPy's operations on arrays are element-wise. You can multiply an array by a number, and that operation will be applied to every element in the array*

In [37]:
import numpy as np
# Given data
unit_costs_data = [45, 60, 55, 70, 80] # In INR
# Write your code below this line
unit_cost=np.array(unit_costs_data)
print("Create a 1-D NumPy array named unit_costs:")
print(f"unit_costs:{unit_cost}")

Create a 1-D NumPy array named unit_costs:
unit_costs:[45 60 55 70 80]


In [38]:
# Define a variable profit_margin_percent with a value of 25
profit_margin_percent=25
print(f"profit margin percent:{profit_margin_percent}")

profit margin percent:25


In [39]:
# Calculate the selling price for each unit by adding the profit margin
print("Calculate the selling price for each unit by adding the profit margin:")
selling_price = unit_cost + (unit_cost * profit_margin_percent / 100)
print(f"selling price : {selling_price}")

Calculate the selling price for each unit by adding the profit margin:
selling price : [ 56.25  75.    68.75  87.5  100.  ]


# **Problem 4: Inventory Management with Broadcasting**

You need to update inventory levels for various ingredients. You have the starting inventory and the ingredients used per
batch for three different flavors. All ingredient amounts are in kilograms (kg).
#### **Task 4.1:** Create a 2-D NumPy array named ingredients_used. The rows represent three flavors and the columns represent three ingredients
#### (e.g., 'Vanilla', 'Chocolate', 'Fruits').
#### **Task 4.2:** Create a 1-D NumPy array named batches_produced representing the number of batches for each flavor.
#### **Task 4.3:** Use NumPy broadcasting to calculate the total amount of each ingredient used across all batches. Print the result.
##### *Hint: You might need to change the shape of one of the arrays to allow broadcasting. Use .reshape() or to make a 1-D array compatible with a 2-D array for element-wise multiplication* 

In [40]:
 # Given data
 # rows: Flavors (A, B, C)
 # cols: Ingredients (Vanilla, Chocolate, Fruit)
ingredients_used_per_batch = [
 [0.5, 0.3, 0.1],
 [0.2, 0.6, 0.0],
 [0.4, 0.2, 0.3]
 ]
#batches_produced_data = [100, 150, 200]
 # Write your code below this line
ingredients_used=np.array(ingredients_used_per_batch)
print("Create a 2-D NumPy array:")
print(ingredients_used)

Create a 2-D NumPy array:
[[0.5 0.3 0.1]
 [0.2 0.6 0. ]
 [0.4 0.2 0.3]]


In [45]:
# Create a 1-D NumPy array named batches_produced representing the number of batches for each flavor
batches_produced_data = [100, 150, 200]
batches_produced=np.array(batches_produced_data)
print(f"The number of batches for each flavor: {batches_produced}")

The number of batches for each flavor: [100 150 200]


In [66]:
# Use NumPy broadcasting to calculate the total amount of each ingredient used across all batches. Print the result
batches_produced_data = [100, 150, 200]
batch_reshape=batches_produced.reshape(3,1)
print(batch_reshape)
total_amount=ingredients_used*batch_reshape
print(f"the total amount of each ingredient used across all batches:")
print(total_amount)
#optional
print("total amount of each batches:")
total_amount_sum=total_amount.sum(axis=0)
print(total_amount_sum)

[[100]
 [150]
 [200]]
the total amount of each ingredient used across all batches:
[[50. 30. 10.]
 [30. 90.  0.]
 [80. 40. 60.]]
total amount of each batches:
[160. 160.  70.]
